### ISSUE TITLE
Feature request: Timer

### ISSUE THREAD

**Issue by suleimant** [Bre77/myair#12]
Hi, hope you have been well.

I might have missed it but the current integration doesnt pull in the timer on the unit "countDownToOff" and "countDownToOn". Any chance of adding this?  

As an aside- the freshairstatus (For the fresh air return) might also be auseful addition (I am planning to add this to my install next year) so more a forward looking item?

Thanks

**Comment by Bre77** [comment]
This should all be possible and a good reason for me to learn about custom services.

Would you just see there being a service for setting each of these? I can't see how they would map to any existing entities.

Their values are already in the climate entities attributes, but I may also create sensors to report their values.

**Comment by suleimant** [comment]
Yes, I think so- on the timers- with the manual configuration via yaml I had previously. I set it up as a sensor and then had an automation to adjust the timer (worked better than the android app as it was more granular than the 30 min intervals!)

No idea on the freshair status as thats next years problem! Current project is it to make my air to water heatpump "smart"!

**Comment by Bre77** [comment]
A work in progress version is in the Dev branch, has working fresh air (if support by your system), a clean filter sensor, and time to sensors. I just need to get the service working correctly.

**Comment by suleimant** [comment]
I'll test this weekend and also see if I can assist with this. Thanks

**Comment by Bre77** [comment]
I have pushed the service code to dev, appears to be working.

![image](https://user-images.githubusercontent.com/2647914/91622875-81530500-e9dc-11ea-8aec-f064d9eb6983.png)

**Comment by suleimant** [comment]
thanks- setup some automations and now have it working via a slider as well 👍 
Appreciate it

**Comment by Bre77** [comment]
Thanks @suleimant, just a heads up when I push this out to master today, the service has been renamed to "myair.set_time_to"

**Comment by SeanoNET** [comment]
Hi, Is there anyway to set the timer from HA? I am more interested in setting the time to off, but is this possible in the current build?

**Comment by Bre77** [comment]
This is already implemented with a custom service. See the documentation:

https://www.home-assistant.io/integrations/advantage_air/

**Comment by Bre77** [comment]
> Hi, Is there anyway to set the timer from HA? I am more interested in setting the time to off, but is this possible in the current build?

This is already implemented in the core integration, with a custom service. See the documentation:

https://www.home-assistant.io/integrations/advantage_air/

**Comment by SeanoNET** [comment]
Thanks! @Bre77
