### ISSUE TITLE
Motion sensors detected when not present

### ISSUE THREAD

**Issue by dwooner** [Bre77/myair#14]
When adding the integration, it finds a motion sensor in each zone, yet I have none installed.  Creates 4 binary_sensor entities as below:

binary_sensor.bedrooms_motion
binary_sensor.living_motion
binary_sensor.master_suite_motion
binary_sensor.theatre_motion

As you can see below, motionConfig is 0, which I would assume means motion sensor not present.

getSystemData below:

{"aircons":{"ac1":{"info":{"aaAutoFanModeEnabled":true,"activationCodeStatus":"noCode","airconErrorCode":"","cbFWRevMajor":6,"cbFWRevMinor":2,"cbType":0,"climateControlModeIsRunning":false,"constant1":4,"constant2":0,"constant3":0,"countDownToOff":0,"countDownToOn":0,"fan":"low","filterCleanStatus":0,"freshAirStatus":"none","mode":"vent","myAutoModeCurrentSetMode":"vent","myAutoModeIsRunning":false,"myZone":0,"name":"AC","noOfConstants":1,"noOfZones":4,"quietNightModeEnabled":false,"quietNightModeIsRunning":false,"rfSysID":2,"setTemp":24.0,"state":"off","uid":"001ec0d334c7","unitType":17},"zones":{"z01":{"error":0,"maxDamper":100,"measuredTemp":0.0,"minDamper":0,"motion":0,"motionConfig":0,"name":"MASTER SUITE","number":1,"rssi":0,"setTemp":24.0,"state":"open","value":55,"type":0,"tempSensorClash":false},"z02":{"error":0,"maxDamper":100,"measuredTemp":0.0,"minDamper":0,"motion":0,"motionConfig":0,"name":"BEDROOMS","number":2,"rssi":0,"setTemp":24.0,"state":"close","value":10,"type":0,"tempSensorClash":false},"z03":{"error":0,"maxDamper":100,"measuredTemp":0.0,"minDamper":0,"motion":0,"motionConfig":0,"name":"THEATRE","number":3,"rssi":0,"setTemp":24.0,"state":"close","value":10,"type":0,"tempSensorClash":false},"z04":{"error":0,"maxDamper":100,"measuredTemp":0.0,"minDamper":0,"motion":0,"motionConfig":0,"name":"LIVING","number":4,"rssi":0,"setTemp":24.0,"state":"open","value":10,"type":0,"tempSensorClash":false}}}},"myAddOns":{"hueBridges":{},"hueBridgesOrder":[]},"myLights":{"groups":{},"groupsOrder":[],"lights":{},"system":{"sunsetTime":"06:20 PM"}},"myMonitors":{"monitors":{},"monitorsOrder":[]},"myScenes":{"scenes":{"s0":{"aircons":{"ac1":{"info":{"fan":"low","freshAirStatus":"none","mode":"heat","myZone":0,"name":"AC","setTemp":22.0,"state":"off","uid":"001ec0d334c7"},"zones":{"z01":{"motionConfig":0,"number":1,"setTemp":24.0,"state":"open","value":15,"tempSensorClash":false},"z02":{"motionConfig":0,"number":2,"setTemp":24.0,"state":"close","value":20,"tempSensorClash":false},"z03":{"motionConfig":0,"number":3,"setTemp":24.0,"state":"close","value":20,"tempSensorClash":false},"z04":{"motionConfig":0,"number":4,"setTemp":24.0,"state":"open","value":65,"tempSensorClash":false}}}},"id":"s0","lights":{},"monitors":{},"name":"MyUndo","summary":"Days this scene will run:\nnone\n\nMyAir:\nAircon: off","things":{}}},"scenesOrder":[]},"mySensors":{"sensors":{},"sensorsOrder":[]},"myThings":{"groups":{},"groupsOrder":[],"system":{},"things":{}},"system":{"aaServiceRev":"14.116","allTspErrorCodes":{},"country":"Australia","dealerPhoneNumber":"1300850191","deviceIds":["2288rIn3K8XEocR0wMytrqwUiNR2","6B0fQ8w0CvaamsH3Od5x9jyxz963","uOOTS0n81iUluI6h7MsGd0wIYqQ2","5ZFTC2GmlrSyfJQgmwln49V7sKk1","GB5iVebh5Igk9UgUbX3rTo0vbkG3"],"deviceIdsV2":{"2288rIn3K8XEocR0wMytrqwUiNR2":"eZ-NgQI4U5w:APA91bGUsEfSu8kahICB7KQ35ITfFgBjper8mbvA6V85NpqZc3_fxDkYLoFJqYoEHlG5PAIoISAjoKGLd6ICWzEnZ3avMGGMidVtm_j-j8M2mvtYfxnbfccOfPlyL7IUlQUAs5GbPAza","5ZFTC2GmlrSyfJQgmwln49V7sKk1":"f8ka_ZFM0ag:APA91bFQAicGacLIcovF_730LzfI9MIeiwnhO7N0iGjgyFMR5-rYp2sS1pOtwt9jxOUnGhPYRxy8F0bfIpvmjyixdT6WOyOQx-zh-Q7JSl8-HKDrRJJb9xvL-j1khO_G4_9-jYnDMjmO","GB5iVebh5Igk9UgUbX3rTo0vbkG3":"et2_M2oCk2Q:APA91bFFTmlivD-_6DRllLm_uApQtMn8DMflVw_38U4XqXrIYkBTd4clo060wJ8eFECsrrrOJnHt7EbTBnI2MVthihN1X5w7luYeGqkix1nsvgUDFrJvhjiuUuTpZGyFQ-g6H8vThwGd","6B0fQ8w0CvaamsH3Od5x9jyxz963":"cabhJcprfYM:APA91bFrZMkT-iMRz3YXaanGiOQAbOgliYsgyCOuiHVJlJPMtkkM1iyujmnuOnH6b2NhgHsmPMsxYrCP1ZC68VrV9t22E8QivA3fkf5buYXYr8edYBzCNVsLfGjCBFpFcvNN8dP5jCy8","uOOTS0n81iUluI6h7MsGd0wIYqQ2":"cH5avH_CRA8:APA91bFoekF5vO9d3hQFic-eHhDukbqcNGC1ZCa5VYeCSOLFVgBH18U25UPuZZHylVcBFEY2kTTFxMzDfVxHOtQJA7gzd1AvGqdF0nQJdTnx_WNsc_se_NEvKdEAi_ajaFBAsbEp8nO7"},"drawLightsTab":false,"drawThingsTab":false,"garageDoorReminderWaitTime":2,"hasAircons":true,"hasLights":false,"hasSensors":false,"hasThings":false,"hasThingsBOG":false,"hasThingsLight":false,"latitude":-32.3222184,"logoPIN":"1234","longitude":115.82851529999999,"mid":"001ec0d334c7","myAppRev":"15.810","name":"MyPlace","needsUpdate":false,"noOfAircons":1,"noOfSnapshots":0,"postCode":"6171","rid":"k6KuJf5vHjYEF5KAdWefIDAKq8i2","showMeasuredTemp":true,"sysType":"MyAir5","tspErrorCode":"noError","tspIp":"192.168.1.4","tspModel":"MyAir5","versions":{}},"snapshots":{}}

**Comment by Bre77** [comment]
So my motionConfig is 1, and I also have no motion sensors. I cant find any solid documentation to confirm this, but I have found a reference to motionConfig set to 2 and a motion value, so I have pushed an update that creates the binary sensors on motionConfig==2 now.

**Comment by Bre77** [comment]
@dwooner can you update from HACS and let me know if this is fixed.

**Comment by Bre77** [comment]
Saw you confirmed it on the other issue. Closing.
