### ISSUE TITLE
UI elements become unavailable - especially after interacting with UI

### ISSUE THREAD

**Issue by dwooner** [Bre77/myair#15]
Frequently after interacting with the Lovelace UI elements for the Aircon (havent tested services yet, but I suspect the same), the UI options become unavailable:
![image](https://user-images.githubusercontent.com/66827314/94984692-38651200-0581-11eb-8b03-b76389e12c1e.png)

Worth noting, is immediately for a few seconds after interacting with the UI, a getSystemData will only return 
{}

This empty result also occurs after interacting with the control tablet or mobile app as well - I suspect the system returns an empty result set whenever any commands are issued
After a second or so, the normal getSystemData complete results are returned.

The unavailable message can persist for quite some time, perhaps 20 seconds or longer.
GetSystemData returns normal full results during this time.  

I think this is due to perhaps polling too soon after a change, and then a subsequent delay between retrying the next "full" poll, resulting in appearing unavailable for several seconds longer than needed.  Perhaps a slightly longer delay in the poll before reaching the 5 times, will return a good result set.

Core log ERROR's:
2020-10-03 13:28:46 ERROR (MainThread) [custom_components.myair] Timeout fetching MyAir data
2020-10-03 13:59:31 ERROR (MainThread) [custom_components.myair] Error fetching MyAir data: Tried 5 times to get MyAir data
2020-10-03 14:00:38 ERROR (MainThread) [custom_components.myair] Error fetching MyAir data: Tried 5 times to get MyAir data
2020-10-03 14:01:51 ERROR (MainThread) [custom_components.myair] Error fetching MyAir data: Tried 5 times to get MyAir data
2020-10-03 14:06:01 ERROR (MainThread) [custom_components.myair] Timeout fetching MyAir data
2020-10-03 14:07:40 ERROR (MainThread) [custom_components.myair] Error fetching MyAir data: Tried 5 times to get MyAir data
2020-10-03 14:08:13 ERROR (MainThread) [custom_components.myair] Error fetching MyAir data: Tried 5 times to get MyAir data

getSystemData:
{"aircons":{"ac1":{"info":{"aaAutoFanModeEnabled":true,"activationCodeStatus":"noCode","airconErrorCode":"","cbFWRevMajor":6,"cbFWRevMinor":2,"cbType":0,"climateControlModeIsRunning":false,"constant1":4,"constant2":0,"constant3":0,"countDownToOff":0,"countDownToOn":0,"fan":"low","filterCleanStatus":0,"freshAirStatus":"none","mode":"vent","myAutoModeCurrentSetMode":"vent","myAutoModeIsRunning":false,"myZone":0,"name":"AC","noOfConstants":1,"noOfZones":4,"quietNightModeEnabled":false,"quietNightModeIsRunning":false,"rfSysID":2,"setTemp":23.0,"state":"off","uid":"001ec0d334c7","unitType":17},"zones":{"z01":{"error":0,"maxDamper":100,"measuredTemp":0.0,"minDamper":0,"motion":0,"motionConfig":0,"name":"MASTER SUITE","number":1,"rssi":0,"setTemp":24.0,"state":"open","value":100,"type":0,"tempSensorClash":false},"z02":{"error":0,"maxDamper":100,"measuredTemp":0.0,"minDamper":0,"motion":0,"motionConfig":0,"name":"BEDROOMS","number":2,"rssi":0,"setTemp":24.0,"state":"close","value":10,"type":0,"tempSensorClash":false},"z03":{"error":0,"maxDamper":100,"measuredTemp":0.0,"minDamper":0,"motion":0,"motionConfig":0,"name":"THEATRE","number":3,"rssi":0,"setTemp":24.0,"state":"open","value":100,"type":0,"tempSensorClash":false},"z04":{"error":0,"maxDamper":100,"measuredTemp":0.0,"minDamper":0,"motion":0,"motionConfig":0,"name":"LIVING","number":4,"rssi":0,"setTemp":24.0,"state":"open","value":100,"type":0,"tempSensorClash":false}}}},"myAddOns":{"hueBridges":{},"hueBridgesOrder":[]},"myLights":{"groups":{},"groupsOrder":[],"lights":{},"system":{"sunsetTime":"06:20 PM"}},"myMonitors":{"monitors":{},"monitorsOrder":[]},"myScenes":{"scenes":{"s0":{"aircons":{"ac1":{"info":{"fan":"low","freshAirStatus":"none","mode":"heat","myZone":0,"name":"AC","setTemp":22.0,"state":"off","uid":"001ec0d334c7"},"zones":{"z01":{"motionConfig":0,"number":1,"setTemp":24.0,"state":"open","value":15,"tempSensorClash":false},"z02":{"motionConfig":0,"number":2,"setTemp":24.0,"state":"close","value":20,"tempSensorClash":false},"z03":{"motionConfig":0,"number":3,"setTemp":24.0,"state":"close","value":20,"tempSensorClash":false},"z04":{"motionConfig":0,"number":4,"setTemp":24.0,"state":"open","value":65,"tempSensorClash":false}}}},"id":"s0","lights":{},"monitors":{},"name":"MyUndo","summary":"Days this scene will run:\nnone\n\nMyAir:\nAircon: off","things":{}}},"scenesOrder":[]},"mySensors":{"sensors":{},"sensorsOrder":[]},"myThings":{"groups":{},"groupsOrder":[],"system":{},"things":{}},"system":{"aaServiceRev":"14.116","allTspErrorCodes":{},"country":"Australia","dealerPhoneNumber":"1300850191","deviceIds":["2288rIn3K8XEocR0wMytrqwUiNR2","6B0fQ8w0CvaamsH3Od5x9jyxz963","uOOTS0n81iUluI6h7MsGd0wIYqQ2","5ZFTC2GmlrSyfJQgmwln49V7sKk1","GB5iVebh5Igk9UgUbX3rTo0vbkG3"],"deviceIdsV2":{"2288rIn3K8XEocR0wMytrqwUiNR2":"eZ-NgQI4U5w:APA91bGUsEfSu8kahICB7KQ35ITfFgBjper8mbvA6V85NpqZc3_fxDkYLoFJqYoEHlG5PAIoISAjoKGLd6ICWzEnZ3avMGGMidVtm_j-j8M2mvtYfxnbfccOfPlyL7IUlQUAs5GbPAza","5ZFTC2GmlrSyfJQgmwln49V7sKk1":"f8ka_ZFM0ag:APA91bFQAicGacLIcovF_730LzfI9MIeiwnhO7N0iGjgyFMR5-rYp2sS1pOtwt9jxOUnGhPYRxy8F0bfIpvmjyixdT6WOyOQx-zh-Q7JSl8-HKDrRJJb9xvL-j1khO_G4_9-jYnDMjmO","GB5iVebh5Igk9UgUbX3rTo0vbkG3":"et2_M2oCk2Q:APA91bFFTmlivD-_6DRllLm_uApQtMn8DMflVw_38U4XqXrIYkBTd4clo060wJ8eFECsrrrOJnHt7EbTBnI2MVthihN1X5w7luYeGqkix1nsvgUDFrJvhjiuUuTpZGyFQ-g6H8vThwGd","6B0fQ8w0CvaamsH3Od5x9jyxz963":"cabhJcprfYM:APA91bFrZMkT-iMRz3YXaanGiOQAbOgliYsgyCOuiHVJlJPMtkkM1iyujmnuOnH6b2NhgHsmPMsxYrCP1ZC68VrV9t22E8QivA3fkf5buYXYr8edYBzCNVsLfGjCBFpFcvNN8dP5jCy8","uOOTS0n81iUluI6h7MsGd0wIYqQ2":"cH5avH_CRA8:APA91bFoekF5vO9d3hQFic-eHhDukbqcNGC1ZCa5VYeCSOLFVgBH18U25UPuZZHylVcBFEY2kTTFxMzDfVxHOtQJA7gzd1AvGqdF0nQJdTnx_WNsc_se_NEvKdEAi_ajaFBAsbEp8nO7"},"drawLightsTab":false,"drawThingsTab":false,"garageDoorReminderWaitTime":2,"hasAircons":true,"hasLights":false,"hasSensors":false,"hasThings":false,"hasThingsBOG":false,"hasThingsLight":false,"latitude":-32.3222184,"logoPIN":"1234","longitude":115.82851529999999,"mid":"001ec0d334c7","myAppRev":"15.810","name":"MyPlace","needsUpdate":false,"noOfAircons":1,"noOfSnapshots":0,"postCode":"6171","rid":"k6KuJf5vHjYEF5KAdWefIDAKq8i2","showMeasuredTemp":true,"sysType":"MyAir5","tspErrorCode":"noError","tspIp":"192.168.1.4","tspModel":"MyAir5","versions":{}},"snapshots":{}}

**Comment by Bre77** [comment]
Curious, it's trying 5 times and still failing. If it gets {} back it retrys a second later. It's possible your system need more time. I'll investigate.

**Comment by dwooner** [comment]
OK, cool, so that's a total of 4 seconds, correct ?
Try 1
wait 1 second
Try 2
wait 1 second
Try 3
wait 1 second
Try 4
wait 1 second
Try 5

But even then, it stays unavailable for a good 10 or 15 seconds longer sometimes, even if I F5 refresh or even force reload the UI page - is this a lovelace UI refresh interval thing ?

For example, if the AC is on heat and I turn it off, pressing F5 refresh shows the aircon is still on and heating.  It doesn't update to show the AC is off for several seconds longer.

**Comment by dwooner** [comment]
Further testing here - seems to consistently take anywhere between 4.5 and 7 seconds to start returning the full getSystemData result set again.  I've got the "old" Android 4 wall mounted tablet, if that makes any difference.

**Comment by Bre77** [comment]
So the 15 second delay is the polling interval set by my integration, which perfectly explains why it takes that long to correct. Now it does seem your hardware is just slower than mine and others, so for now I have change the following:

- Refresh occurs 1 second after changes (previously was immediately)
- Retry wait time goes up by 1 second each try, meaning the max wait time is now 1+2+3+4=10 seconds, rather than 4 seconds.
- If its still failing after 10 seconds, the next refresh is only 5 seconds later anyway with the 15 second polling interval.

Hopefully that helps your setup, and if we have success I'll push similar changes upstream into the Pypi library that I wrote for the core integration.

**Comment by dwooner** [comment]
new version can't add via integration - fails without a UI error - Log says:
2020-10-05 16:42:40 ERROR (MainThread) [custom_components.myair.config_flow] Unable to connect to MyAir: Cannot connect to host 192.168.1.4:2025 ssl:default [Connect call failed ('192.168.1.4', 2025)]

Can confirm URL is correct and active in a browser (http://192.168.1.4:2025/)

**Comment by Bre77** [comment]
I occasionally got those setup errors, and a restart almost always fixed it. I suspect it also needs some retry logic for the setup checks.
