### ISSUE TITLE
Error in the HA Logs

### ISSUE THREAD

**Issue by Rossco88** [Bre77/myair#16]
File "/config/custom_components/myair/sensor.py", line 122, in icon
    return ["mdi:fan-off","mdi:fan"][self.coordinator.data['aircons'][self.acx]['zones'][self.zx]['state'] == MYAIR_ZONE_OPEN]
NameError: name 'MYAIR_ZONE_OPEN' is not defined

**Comment by Bre77** [comment]
Well that's a pretty stupid bug, Fixed in the latest push.
