### ISSUE TITLE
blacklisted

### ISSUE THREAD

**Issue by tcarlsen** [Bre77/myair#18]
Not using your integration but got this in my logs:

```
Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:34 
Integration: HACS (documentation, issues) 
First occurred: 1.01.48 (1 occurrences) 
Last logged: 1.01.48

Bre77/myair - Repository is in the blacklist.
```

**Comment by antisane** [comment]
Strange thing is this: I don't even have this integration installed, and yet I get the blacklisted "error" in my logs too...

**Comment by uherting** [comment]
My HA supervised on Ubuntu / docker says:
2021-02-23 07:01:47 ERROR (MainThread) [custom_components.hacs] Bre77/myair - Repository is in the blacklist.

**Comment by Bre77** [comment]
You should probably raise this issue on the HACS repo, as there isn't anything I can really do to address it.

I did recently add this repo to the blacklist as it is now an integration in core.
