### ISSUE TITLE
Lost climate entities

### ISSUE THREAD

**Issue by ShonkyCH** [Bre77/myair#6]
I previously had climate.zonename entities. With the most recent updates they seem to have disappeared.

I do have these entities for the all the valid zones:
cover.zonename_vent
binary_sensor.zonename_motion
sensor.zonename_signal 

No errors are being reported. Am I missing something obvious?

I do have the one entity called climate.ac for the master control that works and changes the mode, temperature, on/off etc.  Its temperature does control the "myzone" selected zone, but doesn't work in reverse. Mine has been 16C since it was installed. That's a separate issue.

**Comment by Bre77** [comment]
I have removed climate.<zone> and replaced it with cover.<zone>, as my **e-zone** system has no purpose in setting temperatures in each zone, and I don't have temperature readings. Obviously this isn't the case for you and other MyAir users, so I will re-enable this.

**Comment by ShonkyCH** [comment]
Thanks. Yeah I have the individual sensors and as such the master temp doesn't actually do anything on mine so I'd just hide that entity.

Does your version have the variable dampers or are they just open/closed? Mine open in steps of 5% to control the temperature so might be specific with the temperature sensor option.

**Comment by Bre77** [comment]
I also have variable dampers, and that's what the cover.* entities are for. 0% is closed, 5% steps after that. If you set the Fan Speed on the climate.* for each zone, it uses 0% for Off, 30% for Low, 60% for Medium, and 100% for High. I have pushed a change that enables climate zones IF measured temp is greater than 0. I believe without a measured temp the zone temps are useless, is that right? I may just enable the zone entities regardless.... I am unsure whats best here.

**Comment by Bre77** [comment]
OK I figured it out. Your zones are "type": 1, my zones are "type": 0.

> Zone type - 0 means percentage (use value to change), any other number means it's temperature control, use setTemp.

As such I will enable climate and damper sensor for type 1, and cover for type 0.

**Comment by Bre77** [comment]
Fixed in latest merge, using zone types.
