### ISSUE TITLE
Integration not detecting climate or sensor

### ISSUE THREAD

**Issue by suleimant** [Bre77/myair#8]
**Error log from HASSIO after installing integration:**

Logger: homeassistant.components.climate
Source: custom_components/myair/climate.py:174
Integration: Climate (documentation, issues)
First occurred: 18:40:50 (1 occurrences)
Last logged: 18:40:50

Error while setting up myair platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/myair/climate.py", line 54, in async_setup_entry
    entities.append(MyAirZone(my, acx, zx))
  File "/config/custom_components/myair/climate.py", line 174, in __init__
    self.coordinator = hass.data[DOMAIN]['coordinator']
AttributeError: 'dict' object has no attribute 'data'

Logger: homeassistant.components.climate
Source: custom_components/myair/climate.py:174
Integration: Climate (documentation, issues)
First occurred: 18:40:50 (1 occurrences)
Last logged: 18:40:50

Error while setting up myair platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/myair/climate.py", line 54, in async_setup_entry
    entities.append(MyAirZone(my, acx, zx))
  File "/config/custom_components/myair/climate.py", line 174, in __init__
    self.coordinator = hass.data[DOMAIN]['coordinator']
AttributeError: 'dict' object has no attribute 'data'

**JSON from myair:**
{
  "aircons": {
    "ac1": {
      "info": {
        "aaAutoFanModeEnabled": true,
        "activationCodeStatus": "noCode",
        "airconErrorCode": "",
        "cbFWRevMajor": 7,
        "cbFWRevMinor": 8,
        "cbType": 1,
        "climateControlModeIsRunning": false,
        "constant1": 9,
        "constant2": 5,
        "constant3": 0,
        "countDownToOff": 0,
        "countDownToOn": 0,
        "fan": "high",
        "filterCleanStatus": 0,
        "freshAirStatus": "none",
        "mode": "heat",
        "myAutoModeCurrentSetMode": "heat",
        "myAutoModeIsRunning": false,
        "myZone": 0,
        "name": "AC??",
        "noOfConstants": 2,
        "noOfZones": 10,
        "quietNightModeEnabled": true,
        "quietNightModeIsRunning": false,
        "rfSysID": 2,
        "setTemp": 23,
        "state": "off",
        "uid": "d88039efb59e",
        "unitType": 24
      },
      "zones": {
        "z01": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 0,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "Dummy",
          "number": 1,
          "rssi": 0,
          "setTemp": 21,
          "state": "close",
          "value": 20,
          "type": 0,
          "tempSensorClash": false
        },
        "z02": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 16.5,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "Kids room",
          "number": 2,
          "rssi": 38,
          "setTemp": 22,
          "state": "open",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        },
        "z03": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 17.2,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "Guest room",
          "number": 3,
          "rssi": 37,
          "setTemp": 22,
          "state": "close",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        },
        "z04": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 17,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "Spare room",
          "number": 4,
          "rssi": 42,
          "setTemp": 22,
          "state": "close",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        },
        "z05": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 15.2,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "TV Room",
          "number": 5,
          "rssi": 17,
          "setTemp": 22,
          "state": "close",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        },
        "z06": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 16,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "EntranceHall",
          "number": 6,
          "rssi": 44,
          "setTemp": 22,
          "state": "close",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        },
        "z07": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 17.7,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "Study",
          "number": 7,
          "rssi": 49,
          "setTemp": 22,
          "state": "close",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        },
        "z08": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 19.2,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "Kitchen",
          "number": 8,
          "rssi": 41,
          "setTemp": 22,
          "state": "close",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        },
        "z09": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 19.9,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "Common Areas",
          "number": 9,
          "rssi": 51,
          "setTemp": 22,
          "state": "open",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        },
        "z10": {
          "error": 0,
          "maxDamper": 100,
          "measuredTemp": 17.1,
          "minDamper": 0,
          "motion": 0,
          "motionConfig": 0,
          "name": "Main bedroom",
          "number": 10,
          "rssi": 36,
          "setTemp": 22,
          "state": "open",
          "value": 100,
          "type": 1,
          "tempSensorClash": false
        }
      }
    }
  },
  "myAddOns": {
    "hueBridges": {},
    "hueBridgesOrder": []
  },
  "myLights": {
    "groups": {},
    "groupsOrder": [],
    "lights": {},
    "system": {
      "sunsetTime": "05:55 PM"
    }
  },
  "myMonitors": {
    "monitors": {},
    "monitorsOrder": []
  },
  "myScenes": {
    "scenes": {
      "s0": {
        "aircons": {
          "ac1": {
            "info": {
              "fan": "high",
              "freshAirStatus": "none",
              "mode": "heat",
              "myZone": 0,
              "name": "AC??",
              "setTemp": 23,
              "state": "off",
              "uid": "d88039efb59e"
            },
            "zones": {
              "z01": {
                "motionConfig": 0,
                "number": 1,
                "setTemp": 21,
                "state": "close",
                "value": 20,
                "tempSensorClash": false
              },
              "z02": {
                "motionConfig": 0,
                "number": 2,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              },
              "z03": {
                "motionConfig": 0,
                "number": 3,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z04": {
                "motionConfig": 0,
                "number": 4,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z05": {
                "motionConfig": 0,
                "number": 5,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z06": {
                "motionConfig": 0,
                "number": 6,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z07": {
                "motionConfig": 0,
                "number": 7,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z08": {
                "motionConfig": 0,
                "number": 8,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z09": {
                "motionConfig": 0,
                "number": 9,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              },
              "z10": {
                "motionConfig": 0,
                "number": 10,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              }
            }
          }
        },
        "id": "s0",
        "name": "MyUndo",
        "summary": "Days this scene will run:\nnone\n\nAircon: off"
      },
      "s10001": {
        "activeDays": 62,
        "airconStopTime": 465,
        "airconStopTimeEnabled": true,
        "aircons": {
          "ac1": {
            "info": {
              "fan": "high",
              "freshAirStatus": "none",
              "mode": "heat",
              "myZone": 0,
              "name": "Aircon",
              "setTemp": 23,
              "state": "on",
              "uid": "d88039efb59e"
            },
            "zones": {
              "z01": {
                "motionConfig": 0,
                "number": 1,
                "setTemp": 21,
                "state": "close",
                "value": 20,
                "tempSensorClash": false
              },
              "z02": {
                "motionConfig": 0,
                "number": 2,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              },
              "z03": {
                "motionConfig": 0,
                "number": 3,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z04": {
                "motionConfig": 0,
                "number": 4,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z05": {
                "motionConfig": 0,
                "number": 5,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z06": {
                "motionConfig": 0,
                "number": 6,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z07": {
                "motionConfig": 0,
                "number": 7,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z08": {
                "motionConfig": 0,
                "number": 8,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z09": {
                "motionConfig": 0,
                "number": 9,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              },
              "z10": {
                "motionConfig": 0,
                "number": 10,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              }
            }
          }
        },
        "id": "s10001",
        "lights": {},
        "myTimeEnabled": false,
        "name": "Morning week",
        "startTime": 375,
        "summary": "Days this scene will run:\nMonday, Tuesday, Wednesday, Thursday, Friday\n\nAircon: on, mode: heat, fan speed: high, 23Â°C\nopen zones:\nKids room, Common Areas, Main b/room",
        "things": {},
        "timerEnabled": true
      },
      "s10002": {
        "activeDays": 65,
        "airconStopTime": 480,
        "airconStopTimeEnabled": true,
        "aircons": {
          "ac1": {
            "info": {
              "fan": "auto",
              "freshAirStatus": "none",
              "mode": "heat",
              "myZone": 0,
              "name": "AC??",
              "setTemp": 23,
              "state": "on",
              "uid": "d88039efb59e"
            },
            "zones": {
              "z01": {
                "motionConfig": 0,
                "number": 1,
                "setTemp": 21,
                "state": "close",
                "value": 20,
                "tempSensorClash": false
              },
              "z02": {
                "motionConfig": 0,
                "number": 2,
                "setTemp": 21,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z03": {
                "motionConfig": 0,
                "number": 3,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z04": {
                "motionConfig": 0,
                "number": 4,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z05": {
                "motionConfig": 0,
                "number": 5,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              },
              "z06": {
                "motionConfig": 0,
                "number": 6,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z07": {
                "motionConfig": 0,
                "number": 7,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z08": {
                "motionConfig": 0,
                "number": 8,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              },
              "z09": {
                "motionConfig": 0,
                "number": 9,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              },
              "z10": {
                "motionConfig": 0,
                "number": 10,
                "setTemp": 21,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              }
            }
          }
        },
        "id": "s10002",
        "lights": {},
        "myTimeEnabled": false,
        "name": "Morning wknd",
        "startTime": 390,
        "summary": "Days this scene will run:\nSaturday, Sunday\n\nAircon: on, mode: heat, fan speed: auto, 23Â°C\nopen zones:\nTV Room, Kitchen, Common Areas, Main b/room",
        "things": {},
        "timerEnabled": false
      },
      "s10003": {
        "activeDays": 0,
        "airconStopTime": 1395,
        "airconStopTimeEnabled": true,
        "aircons": {
          "ac1": {
            "info": {
              "fan": "high",
              "freshAirStatus": "none",
              "mode": "cool",
              "myZone": 0,
              "name": "Aircon",
              "setTemp": 21,
              "state": "on",
              "uid": "d88039efb59e"
            },
            "zones": {
              "z01": {
                "motionConfig": 0,
                "number": 1,
                "setTemp": 21,
                "state": "close",
                "value": 20,
                "tempSensorClash": false
              },
              "z02": {
                "motionConfig": 0,
                "number": 2,
                "setTemp": 22,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              },
              "z03": {
                "motionConfig": 0,
                "number": 3,
                "setTemp": 22,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z04": {
                "motionConfig": 0,
                "number": 4,
                "setTemp": 23,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z05": {
                "motionConfig": 0,
                "number": 5,
                "setTemp": 24,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z06": {
                "motionConfig": 0,
                "number": 6,
                "setTemp": 23,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z07": {
                "motionConfig": 0,
                "number": 7,
                "setTemp": 21,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z08": {
                "motionConfig": 0,
                "number": 8,
                "setTemp": 23,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z09": {
                "motionConfig": 0,
                "number": 9,
                "setTemp": 24,
                "state": "close",
                "value": 100,
                "tempSensorClash": false
              },
              "z10": {
                "motionConfig": 0,
                "number": 10,
                "setTemp": 23,
                "state": "open",
                "value": 100,
                "tempSensorClash": false
              }
            }
          }
        },
        "id": "s10003",
        "lights": {},
        "myTimeEnabled": false,
        "name": "Night",
        "startTime": 1275,
        "summary": "Days this scene will run:\nnone\n\nAircon: on, mode: cool, fan speed: high, 21Â°C\nopen zones:\nKids room, Main b/room",
        "things": {},
        "timerEnabled": false
      }
    },
    "scenesOrder": [
      "s10001",
      "s10002",
      "s10003"
    ]
  },
  "mySensors": {
    "sensors": {},
    "sensorsOrder": []
  },
  "myThings": {
    "groups": {},
    "groupsOrder": [],
    "system": {},
    "things": {}
  },
  "system": {
    "aaServiceRev": "14.116",
    "allTspErrorCodes": {},
    "country": "South Africa",
    "dealerPhoneNumber": "",
    "deviceIds": [_removed_    ],
    "deviceIdsV2": {_removed_ },
    "drawLightsTab": false,
    "drawThingsTab": false,
    "garageDoorReminderWaitTime": 2,
    "hasAircons": true,
    "hasLights": false,
    "hasSensors": false,
    "hasThings": false,
    "hasThingsBOG": false,
    "hasThingsLight": false,
    "latitude": _removed_,
    "logoPIN": _removed_,
    "longitude": _removed_,
    "mid": _removed_
    "myAppRev": "15.808",
    "name": "e-Zone",
    "needsUpdate": false,
    "noOfAircons": 1,
    "noOfSnapshots": 0,
    "postCode": _removed_,
    "rid": _removed_
    "showMeasuredTemp": true,
    "sysType": "e-zone",
    "tspErrorCode": "noError",
    "tspIp": "192.168.1.15",
    "tspModel": "e-zone2",
    "versions": {}
  },
  "snapshots": {}
}

**Comment by Bre77** [comment]
Thanks @suleimant, I have just pushed a fix for this bug. Update and let me know if it works.

**Comment by suleimant** [comment]
Thanks for resolving. Working perfectly now 
Appreciate the effort. My yaml files were messy with the previous method of setting this all up!
