### ISSUE TITLE
Unable to add integration from UI via Configuration -> Integrations

### ISSUE THREAD

**Issue by samlorimer** [Bre77/myair#9]
I installed this custom integration via HACS, have since had several restarts of HA (current version 0.114.3)

I cannot add the integration via the UI flow, it doesn't show up from the Configuration -> Integrations ->  +  flow.  There is nothing named "MyAir & e-zone" or similar.

Any ideas?

**Comment by SeanoNET** [comment]
I cant find it either, nothing in the logs 😔 - tired searching for "Advantage Air" and "MyAir & e-zone" on version 2020.11.0 of HA

**Comment by Bre77** [comment]
@SeanoNET do a CTRL+F5 or hard refresh, HA caches the application list.

Also the Advantage Air integration (which would recommend over MyAir) was added in 0.117.0

**Comment by SeanoNET** [comment]
ahh, I found an update to HA core - updated and it's appearing in the list now! Thanks for the quick response. I am relatively new to the HA ecosystem.
